spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            maxAge: 3600
      server:
        webflux:
          routes:
            - id: identity
              uri: http://${IDENTITY_HOST:127.0.0.1}:${IDENTITY_PORT}
              predicates:
                - Path=/api/identity/**

            - id: identity-swagger
              uri: http://${IDENTITY_HOST:127.0.0.1}:${IDENTITY_PORT}
              predicates:
                - Path=/swagger/identity/**

            - id: core
              uri: http://${CORE_HOST:127.0.0.1}:${CORE_PORT}
              predicates:
                - Path=/api/core/**

            - id: ai
              uri: http://${AI_HOST:127.0.0.1}:${AI_PORT}
              predicates:
                - Path=/api/ai/**

            - id: core-swagger
              uri: http://${CORE_HOST:127.0.0.1}:${CORE_PORT}
              predicates:
                - Path=/swagger/core/**

server:
  port: ${GATEWAY_PORT}
  compression:
    enabled: true
    mime-types: application/json,text/plain,application/xml
    min-response-size: 1024 # 1 KB altı için CPU harcamaya değmez

app:
  security:
    jwt:
      public-key: ${JWT_PUBLIC_KEY:}

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    org.springframework.cloud.gateway: TRACE
